# Generated by Django 3.1.7 on 2021-06-05 11:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210605_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='account',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='account',
            name='education_info',
        ),
        migrations.RemoveField(
            model_name='account',
            name='extra_information',
        ),
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.RemoveField(
            model_name='account',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='military_status',
        ),
        migrations.RemoveField(
            model_name='account',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='account',
            name='spoken_languages',
        ),
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='education_info',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='extra_information',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='military_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='spoken_languages',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
