# Generated by Django 3.1.7 on 2021-06-05 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210605_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('-id',)},
        ),
    ]
