# Generated by Django 3.1.7 on 2021-05-01 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('company', models.CharField(max_length=350)),
                ('job_category', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('temporary', 'Temporary')], default=None, max_length=25)),
                ('date_of_publication', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(default=None, max_length=250)),
                ('job_description', models.TextField(default=None)),
                ('slug', models.SlugField(default=None, editable=False)),
                ('employer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
