# Generated by Django 3.1.7 on 2021-05-03 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
        migrations.AlterModelOptions(
            name='jobs',
            options={'ordering': ('-id',)},
        ),
    ]
