# Generated by Django 3.1.7 on 2021-05-17 16:08

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_auto_20210503_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='employee',
            field=models.ManyToManyField(blank=True, default=None, related_name='employee_apply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=ckeditor.fields.RichTextField(default=None),
        ),
    ]
