# Generated by Django 3.1.7 on 2021-05-31 10:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20210517_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(default=None, max_length=355)),
                ('event_description', ckeditor.fields.RichTextField(default=None)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
            ],
        ),
    ]
